ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "image" TEXT,
ADD COLUMN IF NOT EXISTS "googleId" TEXT,
ADD COLUMN IF NOT EXISTS "authProvider" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Customer_googleId_key" ON "Customer"("googleId");
